// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnadhplotnyylhqgseri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYWRocGxvdG55eWxocWdzZXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjA1MjYsImV4cCI6MjA2ODU5NjUyNn0.GemGs_pcTltY4o2qxKnK7WFk0Mxc3Kt02Sv1GnarUv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});